### ISSUE TITLE
SASL Authentication

### ISSUE THREAD

**Issue by onetwopunch** [BitchX/BitchX1.2#17]
Admittedly I'm a BitchX n00b so maybe this is answered somewhere in the interwebs I haven't looked, but I can't seem to find the answer anywhere. I'm using an already registered nick and trying to connect to freenode, but get this error for every freenode server:

```
$ bitchx my-nick irc.freenode.net
BitchX - Based on EPIC Software Labs epic ircII (1998).
Version (BitchX-1.2.1) -- Date (20141114).
...
��� Connecting to port 6667 of server irc.freenode.net [refnum 0]
-orwell.freenode.net(***)- Looking up your hostname...
-orwell.freenode.net(***)- Checking Ident
-orwell.freenode.net(***)- Found your hostname
-orwell.freenode.net(***)- No Ident response
-orwell.freenode.net(***)- Notice -- You need to identify via SASL to use this server
��� Closing Link: gateway/vpn/privateinternetaccess/account (SASL access only)
��� Connection closed from irc.freenode.net: Remote end closed connection
��� BitchX: Servers exhausted. Restarting.
```

I've looked around for options that might be helpful to identify via SASL, but can't seem to find anything. With other IRC clients, I can connect and then `/msg nickserv` but it seems I can't even establish a connection. Any help here would be great.

**Comment by onetwopunch** [comment]
Welp I'm an idiot and totally missed this wiki from the install guide: https://github.com/BitchX/BitchX1.2/wiki#compiling

**Comment by orhun** [comment]
@onetwopunch My SASL authentication in BitchX seems not working. Which command did you use for it?
